# Generated by Django 4.1.2 on 2022-10-27 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyrics',
            old_name='songs_id',
            new_name='track_id',
        ),
        migrations.RemoveField(
            model_name='song',
            name='artiste_id',
        ),
        migrations.AddField(
            model_name='song',
            name='artiste_bio',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='artiste',
            name='last_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='Song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.song'),
        ),
        migrations.AlterField(
            model_name='lyrics',
            name='content',
            field=models.CharField(max_length=900),
        ),
        migrations.AlterField(
            model_name='song',
            name='Artiste',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste'),
        ),
        migrations.AlterField(
            model_name='song',
            name='date_released',
            field=models.DateField(),
        ),
    ]
